version: "3.9"
services:
  nginx-server:
    image: nginx
    ports:
      - "127.0.0.1:5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  flask-app:
    build:
      dockerfile: Dockerfile
      context: .
    command: python app.py
    volumes:
      - ./src:/user/src/app/

  mongo-db:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "./data:/data/db"
